#!/bin/bash

# Commands should be run in the ansible folder

# Install common utilities
ansible-playbook -i hosts/techday playbooks/ensure-utils-installed.yml

# Install and configure prometheus node_exporter on nodes
ansible-playbook -i hosts/techday playbooks/ensure-prometheus-node-exporter-installed.yml --limit node_hosts

# Install and configure prometheus on master
ansible-playbook -i hosts/techday playbooks/ensure-prometheus-monitor-installed.yml --limit master_hosts

# Install and configure grafana on master
ansible-playbook -i hosts/techday playbooks/ensure-grafana-installed.yml --limit master_hosts

# Install and configure ntp on all hosts
ansible-playbook -i hosts/techday playbooks/ensure-utils-installed.yml