- hosts: master_hosts
  roles:
    - cloudalchemy.prometheus
  vars:
    prometheus_targets:
      node:
      - targets:
        - node1:9100
        - node2:9100
        labels:
          env: techday
    prometheus_scrape_configs:
    - job_name: "prometheus"    # Custom scrape job, here using `static_config`
      metrics_path: "/metrics"
      static_configs:
        - targets:
            - "localhost:9090"
    - job_name: "node"
      file_sd_configs:
        - files:
            - "{{ prometheus_config_dir }}/file_sd/node.yml" # This line loads file created from `prometheus_targets`